# Generated by Django 4.2.3 on 2023-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_rename_no_of_word_uploadedfile_word_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='word_size',
            field=models.IntegerField(default=0),
        ),
    ]
